spring:
  application:
    name: my-blog
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 3000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stdu.entity
  configuration:
    map-underscore-to-camel-case: true
file:
  upload:
    path: D:/uploads/
  access:
    path: /static/uploads/
logging:
  level:
    com.stdu: debug
stdu:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xyu1230fasjk213fbaoi123421obfasdjf
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization